# Generated by Django 6.0.2 on 2026-06-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_active_event_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='finished',
        ),
    ]
