name: ala_el_8ahwa_prod

x-prod-env: &prod-env
  env_file:
    - .env.prod
  environment:
    - DJANGO_ENV=prod

services:
  db: *prod-env

  django-app: *prod-env

  celery-worker: *prod-env

  celery-beat: *prod-env

  nginx:
    ports:
      - "8002:80"
