name: ala_el_8ahwa

x-local-env: &local-env
  env_file:
    - .env.local
  environment:
    - DJANGO_ENV=local

services:
  db: *local-env

  django-app:
    <<: *local-env
    command: sh -c "python manage.py migrate --noinput && python manage.py createcachetable && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app

  celery-worker:
    <<: *local-env
    volumes:
      - .:/app

  celery-beat:
    <<: *local-env
    volumes:
      - .:/app

  nginx:
    ports:
      - "8001:80"
