services:
  db-prod:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    container_name: ala_el_8ahwa_db_prod


  django-app-prod:
    build: .
    depends_on:
      - db-prod
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env.prod
    environment:
      - DJANGO_ENV=prod
    container_name: ala_el_8ahwa_app_prod

  nginx-prod:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./static:/static:ro
    depends_on:
      - django-app-prod
    container_name: ala_el_8ahwa_reverse_proxy_prod


volumes:
  postgres_data: