"""
Django settings for ala_el_8ahwa project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

env = os.getenv('DJANGO_ENV', 'local')
load_dotenv(BASE_DIR / f'.env.{env}')


def required_env(name):
    value = os.getenv(name)
    if not value:
        raise ImproperlyConfigured(
            f"{name} is not set. It is required and has no default; "
            f"add it to .env.{env}. See .env.example for the full list."
        )
    return value


def required_env_list(name):
    return [item.strip() for item in required_env(name).split(",") if item.strip()]


SECRET_KEY = required_env("DB_SECRET_KEY")
DEBUG = os.getenv("DEBUG") == "True"


USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


ALLOWED_HOSTS = required_env_list("DJANGO_ALLOWED_HOSTS")

CSRF_TRUSTED_ORIGINS = required_env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "standard"},
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
}

SECURE_SSL_ENABLED = os.getenv("SECURE_SSL_ENABLED", "False") == "True"

SECURE_SSL_REDIRECT = SECURE_SSL_ENABLED
SESSION_COOKIE_SECURE = SECURE_SSL_ENABLED
CSRF_COOKIE_SECURE = SECURE_SSL_ENABLED
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0")) if SECURE_SSL_ENABLED else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'checkins',
    'core',
    'events',
    'groups',
    'leaderboard',
    'notifications',
    "rest_framework",
    'rest_framework_simplejwt.token_blacklist',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ala_el_8ahwa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ala_el_8ahwa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": required_env("DB_ENGINE"),
        "NAME": required_env("DB_NAME"),
        "USER": required_env("DB_USERNAME"),
        "PASSWORD": required_env("DB_PASSWORD"),
        "HOST": required_env("DB_HOST"),
        "PORT": required_env("DB_PORT")
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "users.User"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT =  BASE_DIR / "staticfiles"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "core.exceptions.exception_handler",
    "NUM_PROXIES": int(os.getenv("NUM_PROXIES", "1")),
    "DEFAULT_THROTTLE_RATES": {
        "login_ip": os.getenv("THROTTLE_LOGIN_IP", "10/min"),
        "login_account": os.getenv("THROTTLE_LOGIN_ACCOUNT", "20/hour"),
        "password_reset_email": os.getenv("THROTTLE_PASSWORD_RESET_EMAIL", "3/hour"),
        "password_reset_ip": os.getenv("THROTTLE_PASSWORD_RESET_IP", "10/hour"),
        "group_messages": os.getenv("THROTTLE_GROUP_MESSAGES", "30/min"),
        "send_invite": os.getenv("THROTTLE_SEND_INVITE", "20/hour"),
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache_table",
    }
}

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@localhost")

CLOUDINARY_URL = os.getenv("CLOUDINARY_URL", "")
AVATAR_SIGNATURE_TTL = int(os.getenv("AVATAR_SIGNATURE_TTL", "600"))
AVATAR_RENDER_SIZE = int(os.getenv("AVATAR_RENDER_SIZE", "256"))
GROUP_IMAGE_RENDER_SIZE = int(os.getenv("GROUP_IMAGE_RENDER_SIZE", "512"))
CHECKIN_PHOTO_RENDER_SIZE = int(os.getenv("CHECKIN_PHOTO_RENDER_SIZE", "1024"))

CHECKIN_RADIUS_METERS = int(os.getenv("CHECKIN_RADIUS_METERS", "200"))

LEADERBOARD_MIN_EVENTS = int(os.getenv("LEADERBOARD_MIN_EVENTS", "3"))

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_TASK_ALWAYS_EAGER", "False") == "True"
CELERY_TASK_IGNORE_RESULT = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

WINNER_FREEZE_INTERVAL = float(os.getenv("WINNER_FREEZE_INTERVAL", "60"))
EVENT_REMINDER_INTERVAL = float(os.getenv("EVENT_REMINDER_INTERVAL", "60"))
EVENT_REMINDER_LEAD_MINUTES = int(os.getenv("EVENT_REMINDER_LEAD_MINUTES", "60"))
EVENT_DELETE_LOCK_MINUTES = int(os.getenv("EVENT_DELETE_LOCK_MINUTES", "60"))

CELERY_BEAT_SCHEDULE = {
    "freeze-due-event-winners": {
        "task": "events.freeze_due_winners",
        "schedule": WINNER_FREEZE_INTERVAL,
    },
    "send-due-event-reminders": {
        "task": "events.send_due_reminders",
        "schedule": EVENT_REMINDER_INTERVAL,
    },
}

PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT", "3600"))
PASSWORD_RESET_DEEP_LINK = os.getenv(
    "PASSWORD_RESET_DEEP_LINK", "alael8ahwa://reset-password"
)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

