# Generated by Django 6.0.2 on 2026-03-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('group_invite', 'Group_Invite'), ('invite_accepted', 'Invite_Accepted'), ('new_member', 'New_Member'), ('new_event', 'New_Event'), ('event_reminder', 'Event_Reminder')], max_length=50),
        ),
    ]
